bundler_args: --without development
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script: bundle exec thor spec
sudo: false
cache: bundler
