before_install:
  - gem update --system 2.7.9
  - gem install bundler:1.17.3
  - rvm @global do gem uninstall did_you_mean
bundler_args: --without development
language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.7
  - 2.5.6
  - 2.6.4
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script: bundle exec thor spec
cache: bundler
