bundler_args: --without development
language: ruby
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - jruby-18mode
  - jruby-19mode
  - jruby-9.1.6.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: ruby-head
  fast_finish: true
script: bundle exec thor spec
sudo: false
cache: bundler
